language: rust

rust:
    - stable

cache: cargo

before_cache: |
  RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin -f
  rustup component add clippy --toolchain stable-x86_64-unknown-linux-gnu

script:
- cargo build
- cargo clippy
- cargo test

after_success: |
  cargo tarpaulin --out Xml
  bash <(curl -s https://codecov.io/bash)
