[package]
name = "rsa-fdh"
version = "0.1.0"
authors = ["phayes <patrick.d.hayes@gmail.com>"]
edition = "2018"

[dependencies]
rsa = { git = "https://github.com/phayes/RSA", branch = "blind_functions", features=["expose-internals"] }
fdh = "0.4.0"
num-bigint-dig = "0.3.0"
rand = "0.6.5"
subtle = "2.0.0"
digest = "0.8.0"
failure = "0.1.5"

[dev-dependencies]
sha2 = "0.8.0"
sha-1 = "0.8.1"
hex = "0.3.2"
rand = "0.6.5"